infrastructure/terraform/modules/activation/main.tf, sql/query/cltv_query_template.sqlx
=> fix deployment and integration testing issues

infrastructure/terraform/main.tf, infrastructure/terraform/modules/activation/main.tf, infrastructure/terraform/modules/dataform-workflow/services.tf, infrastructure/terraform/modules/feature-store/main.tf, infrastructure/terraform/modules/feature-store/variables.tf, infrastructure/terraform/modules/pipelines/main.tf, sql/query/cltv_query_template.sqlx
=> creating artifact repos with terraform

CONTRIBUTING.md, README.md, infrastructure/terraform/README.md, infrastructure/terraform/main.tf, infrastructure/terraform/terraform-sample.tfvars, scripts/common.sh, scripts/generate-tf-backend.sh
Including a Disclaimer and Contributing section on the main README.
=> Updated README.md

README.md, infrastructure/README.md, infrastructure/terraform/README.md
=> Updates to README.md

infrastructure/terraform/modules/pipelines/pipelines.tf
=> Remove cloud build pipelines

infrastructure/terraform/README.md, python/pipelines/compiler.py, python/pipelines/pipeline_ops.py
Fixed TF script to compile tabular workflows pipeline definition without a pre-existing view or table.
=> Fix TF script to compile Tabular Workflows

sql/procedure/customer_lifetime_value_label.sqlx
Implementing labels for purchase propensity and customer ltv for all users. For purchase propensity it was already implemented.
=> Quick-fix features for all users

infrastructure/terraform/modules/dataform-workflow/dataform-workflow.tf
Added solution attribution header to the Dataform workflow
Manually
=> Add solution attribution header to the Dataform workflow

python/ga4_setup/setup.py, templates/activation_type_configuration_template.tpl
1. change MDE and MAS to MAJ
2. scripting for automatic update of existing custom event and custom dimensions
Integration test by running terraform
=> update activation event prefix and updating existing resouces

sql/query/auto_audience_segmentation_query_template.sqlx
only use the date portion of the feature_timestamp field & make use of the pre-created custom dimension for prediction value
=> fix activation issue for auto-segmentation

infrastructure/terraform/modules/dataform-workflow/dataform-workflow.tf, infrastructure/terraform/versions.tf
update userAgent with solution deployment tracking tag
integration tested
=> add deployment tracking

config/config.yaml.tftpl, infrastructure/terraform/main.tf, python/pipelines/components/bigquery/component.py, sql/query/audience_segmentation_query_template.sqlx, sql/query/auto_audience_segmentation_query_template.sqlx, sql/query/cltv_query_template.sqlx, sql/query/invoke_audience_segmentation_training_preparation.sqlx, sql/query/invoke_customer_lifetime_value_training_preparation.sqlx, sql/query/invoke_purchase_propensity_training_preparation.sqlx, sql/query/purchase_propensity_query_template.sqlx
=> [Bug-fix] Tabular Workflow schema update

infrastructure/terraform/main.tf, infrastructure/terraform/modules/activation/main.tf, infrastructure/terraform/modules/activation/variables.tf, infrastructure/terraform/modules/data-store/secretmanager.tf, python/activation/main.py, python/ga4_setup/setup.py, sql/query/audience_segmentation_query_template.sqlx, sql/query/auto_audience_segmentation_query_template.sqlx, sql/query/cltv_query_template.sqlx, sql/query/purchase_propensity_query_template.sqlx, templates/activation_query/audience_segmentation_query_template.sqlx, templates/activation_query/auto_audience_segmentation_query_template.sqlx, templates/activation_query/cltv_query_template.sqlx, templates/activation_query/purchase_propensity_query_template.sqlx, templates/app_payload_template.jinja2
Creating and using decile values for Purchase propensity and customer lifetime value use cases for activation
Creating new custom dimension for use case deciles and audience segmentation prediction value 
in staging environment with test GA4 account
=> Decile for activation

infrastructure/cloudshell/terraform-template.tfvars, infrastructure/terraform/main.tf, infrastructure/terraform/outputs.tf, infrastructure/terraform/terraform-sample.tfvars, infrastructure/terraform/variables.tf, scripts/set-env.sh
=> Fix according to customer installation feedback

python/activation/requirements.txt
=> use dataflow default dependency for cloud storage

docs/ml_specs.md
=> add doc over the features user in the ML training and prediction

docs/ml_specs.md
=> add specification for the ML training target field

templates/activation_query/audience_segmentation_query_template.sqlx, templates/activation_query/auto_audience_segmentation_query_template.sqlx, templates/activation_query/cltv_query_template.sqlx, templates/activation_query/purchase_propensity_query_template.sqlx
=> change the selection of client id

templates/activation_user_import/cltv_csv_export.sqlx
=> remove table alias

infrastructure/terraform/main.tf, python/ga4_setup/setup.py
=> only allow ga4 property with type ordinary

docs/activation.md, python/activation/main.py, templates/activation_query/audience_segmentation_query_template.sqlx, templates/activation_query/auto_audience_segmentation_query_template.sqlx, templates/activation_query/cltv_query_template.sqlx, templates/activation_query/purchase_propensity_query_template.sqlx, templates/app_payload_template.jinja2
=> the the fields session_id and user_id to Measurement Protocol payload

templates/activation_type_configuration_template.tpl
=> remove trailing comma

docs/activation.md
=> add Prerequisites section

.github/dependabot.yaml
This PR add a dependabot.yaml file to automatically create updates on new TF modules
No test needed
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] I have successfully run the E2E tests, and have included the links to the pipeline runs below
- [ X ] I have added tests that prove my fix is effective or that my feature works
- [ X ] New and existing unit tests pass locally with my changes
- [ X ] I have updated any relevant documentation to reflect my changes
- [ X ] I have assigned a reviewer and messaged them
=> feat: add dependabot for automatic updates of tf modules

infrastructure/terraform/modules/activation/main.tf
=> trigger cf update on source code change

DEVELOPMENT.md, infrastructure/cloudshell/tutorial.md, infrastructure/terraform/README.md, infrastructure/terraform/main.tf, infrastructure/terraform/modules/activation/main.tf, infrastructure/terraform/modules/activation/variables.tf, infrastructure/terraform/modules/feature-store/bigquery-procedures.tf, infrastructure/terraform/modules/feature-store/main.tf, infrastructure/terraform/modules/feature-store/variables.tf, infrastructure/terraform/modules/pipelines/pipelines.tf, infrastructure/terraform/modules/pipelines/variables.tf, infrastructure/terraform/variables.tf, notebooks/quick_installation.ipynb, pyproject.toml, scripts/generate-tf-backend.sh
Moving to use uv for the terraform deployment
benefiting from out-of-box 
- python version management
- python package managment
- >10x speed improvement
deployment tested in a integration environment
=> Move to uv

DEVELOPMENT.md, README.md, infrastructure/cloudshell/tutorial.md, infrastructure/terraform/README.md, infrastructure/terraform/main.tf, infrastructure/terraform/modules/activation/main.tf, infrastructure/terraform/modules/activation/variables.tf, infrastructure/terraform/modules/feature-store/bigquery-procedures.tf, infrastructure/terraform/modules/feature-store/main.tf, infrastructure/terraform/modules/feature-store/variables.tf, infrastructure/terraform/modules/pipelines/pipelines.tf, infrastructure/terraform/modules/pipelines/variables.tf, infrastructure/terraform/variables.tf, notebooks/quick_installation.ipynb, pyproject.toml, scripts/generate-tf-backend.sh, templates/activation_query/audience_segmentation_query_template.sqlx, templates/activation_query/auto_audience_segmentation_query_template.sqlx, templates/activation_query/churn_propensity_query_template.sqlx, templates/activation_query/cltv_query_template.sqlx, templates/activation_query/purchase_propensity_query_template.sqlx
=> Rebase Main into Multi-property

infrastructure/terraform/POST-INSTALLATION.md
=> add documentation on how to configure dataform pipeline schedule

templates/activation_query/lead_score_propensity_vbb_query_template.sqlx, templates/activation_query/purchase_propensity_vbb_query_template.sqlx
=> cross reference with last day events for smart bidding activation
